name: Check Pull Request
on:
  workflow_dispatch:
  pull_request:
    types:
      - 'ready_for_review'
      - 'opened'
      - 'reopened'
      - 'synchronize'
env:
  HUSKY: 0
jobs:
  release:
    name: Run npm pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Run validation and tests
        run: npm pack
  
      - name: Trigger Workflow in Another Repository
        env:
          EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          Token: ${{ secrets.WORKFLOW_TRIGGER_SECRET }}
        run: 
            # Set the required variables
            repo_owner="rdkcentral" 
            repo_name="firebolt-apis"  
            event_type="trigger-workflow" 
            OPENRPC_PR_BRANCH="${{ github.event.pull_request.head.ref }}"
    
           curl -H "Authorization:token $Token" -X POST https://api.github.com/repos/rdkcentral/firebolt-apis
           -d "{\"event_type\":\"$event_type\", \"client_payload\":{\"OPENRPC_PR_BRANCH\":\"$OPENRPC_PR_BRANCH\"}}"
