name: Check Pull Request
on:
  workflow_dispatch:
  pull_request:
    types:
      - 'ready_for_review'
      - 'opened'
      - 'reopened'
      - 'synchronize'
env:
  HUSKY: 0
jobs:
  release:
    name: Run npm pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Run validation and tests
        run: npm pack
  trigger_repo_b_workflow:
    name: Trigger Firebolt API Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger MFOS Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: MFOS standalone sanity report - CORE,MANAGE,DISCOVERY  # Workflow in Repo B
          token: ${{ secrets.GITHUB_TOKEN }}
          repo:  rdkcentral/firebolt-apis  
          inputs:
            PR_NAME: ${{ github.event.pull_request.head.ref }}  # Pass Repo A PR branch name to Repo B

